server:
  port: 9090

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 764544585758-pn000ql71tf6uq264k7la3f52lsshqi0.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
  datasource:
    url: jdbc:mysql://localhost:3306/searchForest
    username: root
    password: dlaalsgur5162!

  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: qv0qzHt6CNkWGKj0kcAbhh9dIGKpFEhnRuNo8QzmHJE

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha