server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/searchForest
    username: root
    password: dlaalsgur5162!

  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: qv0qzHt6CNkWGKj0kcAbhh9dIGKpFEhnRuNo8QzmHJE

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha