version: '3.8'

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

  graph-service:
    image: ghcr.io/soopsong/graph-service:latest
    ports:
      - "8002:8002"
    environment:
      - REDIS_HOST=redis  # <-- Redis 접근용
    depends_on:
      - redis
    networks:
      - backend

  papers-service:
    image: ghcr.io/soopsong/papers-service:latest
    ports:
      - "8000:8000"
    networks:
      - backend

  sum-service:
    image: ghcr.io/soopsong/sum-service:latest
    ports:
      - "8004:8004"
    networks:
      - backend

networks:
  backend:
    driver: bridge
